openapi: 3.0.0
info:
  title: MastersBook API
  version: 1.0.0
  description: API para gerenciamento de fichas e mesas de RPG.

servers:
  - url: http://localhost:3000/api
    description: Servidor Local

tags:
  - name: Users
    description: Operações relacionadas a usuários.

paths:
  /users/register:
    post:
      summary: Cadastra um novo usuário
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterInput'
      responses:
        201:
          description: Usuário cadastrado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Usuário cadastrado com sucesso!"
                  user:
                    $ref: '#/components/schemas/UserOutput'
        409:
          description: Conflito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users/login:
    post:
      summary: Realiza o login (Email ou Username)
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInput'
      responses:
        200:
          description: Login bem-sucedido
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Login realizado com sucesso!"
                  user:
                    $ref: '#/components/schemas/UserOutput'
        401:
          description: Credenciais inválidas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /users/profile/{id}:
    get:
      summary: Retorna o perfil público do um usuário pelo ID
      tags: [Users]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          description: ID (UUID) do usuário
      responses:
        200:
          description: Perfil encontrado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileOutput'
        400:
          description: Erro de validação (ID não é um UUID)
        404:
          description: Usuário não encontrado

  /users/update/{id}:
    patch:
      summary: Atualiza os dados do usuário
      tags: [Users]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          description: ID (UUID) do usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "mr_paxe"
                firstName:
                  type: string
                  example: "Paxe"
                lastName:
                  type: string
                  example: "Bagre"
                avatarUrl:
                  type: string
                  format: uri
                  example: "https://meu-site.com/avatar.png"
      responses:
        200:
          description: Perfil atualizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Perfil atualizado com sucesso!"
                  user:
                    $ref: '#/components/schemas/UpdateProfileOutput'
        400:
          description: Erro de validação
        404:
          description: Usuário não encontrado
        409:
          description: Conflito (Username já em uso)    

  /users/delete/{id}:
    delete:
      summary: Apaga a conta de um usuário (Requer senha para confirmação)
      tags: [Users]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          description: ID (UUID) do usuário a ser apagado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [password]
              properties:
                password:
                  type: string
                  format: password
                  example: "sua_senha_aqui"
        responses:
          200:
            description: Perfil apagado com sucesso
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: "Perfil apagado com sucesso!"
          400:
            description: Erro de validação
          401:
            description: Senha incorreta
          404:
            description: Usuário não encontrado

  /characters/create:
    post:
      summary: Cria uma nova ficha de personagem
      tags: [Characters]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstName
                - lastName
                - race
                - class
                - attributes
                - userId
                - systemId
              properties:
                firstName:
                  type: string
                  example: "Sir Paxe"
                lastName:
                  type: string
                  example: "o Bagre"
                race:
                  type: string
                  example: "tritão"
                class:
                  type: string
                  example: "Guerreiro"
                level:
                  type: integer
                  example: 20
                attributes:
                  type: object
                  description: JSON flexível contendo os atributos específicos do sistema de RPG.
                  example: 
                    inteligencia: 20
                    sabedoria: 18
                    forca: 200
                    mana: 100
                    hp: 50
                bio:
                  type: string
                  example: "Um guerreiro valente que se tornou lendário após a batalha contra o Baiacu."
                avatarUrl:
                  type: string
                  format: uri
                  example: "https://meu-site.com/sir_paxe.png"
                userId:
                  type: string
                  format: uuid
                  example: "COLE_O_ID_DO_SEU_USUARIO_AQUI"
                systemId:
                  type: string
                  format: uuid
                  example: "COLE_O_ID_DO_SISTEMA_DND_AQUI"
      responses:
        201:
          description: Ficha criada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Ficha criada com sucesso!"
                  character:
                    type: object
                    # Aqui o Swagger vai mostrar os dados da ficha recém-criada
        400:
          description: Erro de validação - Faltam campos obrigatórios ou formatos inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Usuário ou Sistema de RPG não encontrado no banco de dados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Erro interno no servidor

  /characters/update/{id}:
    patch:
      summary: Atualiza dados de uma ficha (Ex: Alterar HP durante a mesa)
      tags: [Characters]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          description: ID da ficha do personagem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                level:
                  type: integer
                  example: 5
                attributes:
                  type: object
                  description: Envie apenas os atributos que deseja alterar. Eles serão mesclados com os atuais.
                  example:
                    hp: 35
                    mana: 10
      responses:
        200:
          description: Ficha atualizada com sucesso
        400:
          description: Erro de validação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Ficha não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /characters/{id}:
    get:
      summary: Busca os dados completos de uma ficha específica
      tags: [Characters]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          description: ID da ficha de personagem
      responses:
        200:
          description: Ficha encontrada com sucesso
        400:
          description: Erro de validação (ID inválido)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Ficha não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /characters/user/{userId}:
    get:
      summary: Lista todas as fichas de um usuário específico
      tags: [Characters]
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            format: uuid
          description: ID do usuário (User)
      responses:
        200:
          description: Lista de fichas retornada com sucesso (Pode ser um array vazio)

  /characters/delete/{id}:
   delete:
      summary: Apaga permanentemente uma ficha do banco de dados
      tags: [Characters]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          description: ID da ficha a ser apagada
      responses:
        200:
          description: Ficha apagada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Ficha apagada com sucesso!"
        400:
          description: Erro de validação (ID inválido)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Ficha não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse' 

components:
  schemas:
    RegisterInput:
      type: object
      required: [username, firstName, lastName, email, password]
      properties:
        username:
          type: string
          example: mr_paxe
        firstName:
          type: string
          example: Paxe
        lastName:
          type: string
          example: Bagre
        email:
          type: string
          format: email
          example: paxe@gmail.com
        password:
          type: string
          format: password
          example: "senha123"

    LoginInput:
      type: object
      required: [login, password]
      properties:
        login:
          type: string
          description: email ou username
          example: mr_paxe
        password:
          type: string
          format: password
          example: "senha123"

    UserOutput:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        username:
          type: string
          example: mr_paxe
        email:
          type: string
          example: paxe@gmail.com

    ProfileOutput:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        username:
          type: string
          example: mr_paxe
        firstName:
          type: string
          example: Paxe
        lastName:
          type: string
          example: Bagre
        email:
          type: string
          example: paxe@gmail.com
        avatarUrl:
          type: string
          example: https://example.com/avatar.jpg

    UpdateProfileOutput:
      type: object
      properties:
        username:
          type: string
          example: mr_paxe
        firstName:
          type: string
          example: Paxe
        lastName:
          type: string
          example: Bagre
        email:
          type: string
          example: paxe@gmail.com
        avatarUrl:
          type: string
          format: uri
          example: "https://meu-site.com/avatar.png"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Mensagem de erro detalhada aqui."

          